In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Dataset/overview.csv")

In [11]:
new_df = df[["Map", "Player", "Team", "Agents", "Rating", "Average Combat Score"]]

In [12]:
new_df

          Map    Player   Team     Agents  Rating  Average Combat Score
0      Ascent     mazin   MIBR       omen    1.13                   251
1      Ascent    artzin   MIBR       yoru    1.04                   224
2      Ascent   ShahZaM   MIBR       sova    0.92                   170
3      Ascent    liazzi   MIBR    killjoy    0.90                   159
4      Ascent     Pa1nt   MIBR        iso    0.68                   148
...       ...       ...    ...        ...     ...                   ...
10175    Bind   t3xture  Gen.G       raze    1.60                   291
10176    Bind    Meteor  Gen.G     cypher    1.43                   269
10177    Bind     Karon  Gen.G  brimstone    1.20                   217
10178    Bind  Munchkin  Gen.G      viper    1.04                   196
10179    Bind     Lakia  Gen.G       skye    1.02                   147

[10180 rows x 6 columns]

In [13]:
stage = pd.read_csv("Dataset/maps_scores.csv")
stage

,Tournament,Stage,Match Type,Match Name,Map,Team A,Team A Score,Team A Attacker Score,Team A Defender Score,Team A Overtime Score,Team B,Team B Score,Team B Attacker Score,Team B Defender Score,Team B Overtime Score,Duration
0,Champions Tour 2024: Americas Stage 2,Regular Season,Week 1,MIBR vs Leviatán,Ascent,MIBR,9,6,3,NaN,Leviatán,13,7,6,NaN,1:05:24
1,Champions Tour 2024: Americas Stage 2,Regular Season,Week 1,MIBR vs Leviatán,Icebox,MIBR,7,3,4,NaN,Leviatán,13,4,9,NaN,45:04
2,Champions Tour 2024: Americas Stage 2,Regular Season,Week 1,Sentinels vs NRG Esports,Lotus,Sentinels,13,8,5,NaN,NRG Esports,8,4,4,NaN,59:21
3,Champions Tour 2024: Americas Stage 2,Regular Season,Week 1,Sentinels vs NRG Esports,Sunset,Sentinels,14,9,3,2.0,NRG Esports,12,9,3,0.0,1:00:54
4,Champions Tour 2024: Americas Stage 2,Regular Season,Week 1,FURIA vs 100 Thieves,Icebox,FURIA,14,6,6,2.0,100 Thieves,12,6,6,0.0,1:12:51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1013,Champions Tour 2024: Pacific Kickoff,Playoffs,Semifinals,DRX vs Gen.G,Lotus,DRX,8,3,5,NaN,Gen.G,13,4,9,NaN,45:52
1014,Champions Tour 2024: Pacific Kickoff,Playoffs,Grand Final,Paper Rex vs Gen.G,Ascent,Paper Rex,5,5,0,NaN,Gen.G,13,6,7,NaN,57:17
1015,Champions Tour 2024: Pacific Kickoff,Playoffs,Grand Final,Paper Rex vs Gen.G,Split,Paper Rex,13,8,5,NaN,Gen.G,4,0,4,NaN,35:10
1016,Champions Tour 2024: Pacific Kickoff,Playoffs,Grand Final,Paper Rex vs Gen.G,Lotus,Paper Rex,11,7,4,NaN,Gen.G,13,8,5,NaN,49:09
1017,Champions Tour 2024: Pacific Kickoff,Playoffs,Grand Final,Paper Rex vs Gen.G,Bind,Paper Rex,4,4,0,NaN,Gen.G,13,5,8,NaN,31:31

In [16]:
new_stage = stage[["Team A Score", "Team B Score", "Team A", "Team B"]]
new_stage

      Team A Score  Team B Score     Team A       Team B
0                9            13       MIBR     Leviatán
1                7            13       MIBR     Leviatán
2               13             8  Sentinels  NRG Esports
3               14            12  Sentinels  NRG Esports
4               14            12      FURIA  100 Thieves
...            ...           ...        ...          ...
1013             8            13        DRX        Gen.G
1014             5            13  Paper Rex        Gen.G
1015            13             4  Paper Rex        Gen.G
1016            11            13  Paper Rex        Gen.G
1017             4            13  Paper Rex        Gen.G

[1018 rows x 4 columns]

In [18]:
new_stage["Winner"] = new_stage["Team A"] if int(new_stage["Team A Score"]) > int(new_stage["Team B Score"]) else new_stage["Team "]
new_stage

TypeError: cannot convert the series to <class 'int'>